api:
  slack:
    url: https://hooks.slack.com/services/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

server:
  port: 8055

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hhplus_concert_reservation
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379

#   kafka 의존성 추가
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
    admin:
      auto-create: true


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        generate-ddl: true
        format_sql: true
        use_sql_comments: true

#  data:
#    redis:
#      host: localhost
#      port: 6379
#
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE







token:
  processing-queue:
    policy:
      max-limit: 1000