api:
  slack:
    url: https://hooks.slack.com/services/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

server:
  port: 8055

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hhplus_concert_reservation
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        generate-ddl: true

redis:
  host: localhost
  port: 6379