SET FOREIGN_KEY_CHECKS = 0;

-- Drop tables if they exist
DROP TABLE IF EXISTS Booking;
DROP TABLE IF EXISTS ConcertOption_Seat;
DROP TABLE IF EXISTS ConcertOption;
DROP TABLE IF EXISTS Concert;
DROP TABLE IF EXISTS Point;
DROP TABLE IF EXISTS Seat;
DROP TABLE IF EXISTS Token;
DROP TABLE IF EXISTS `User`;
DROP TABLE IF EXISTS WaitingCount;